forest_runner:
  ros__parameters:
    # =========================
    # 话题与服务
    # =========================
    start_signal_topic: "/start_signal"
    next_cmd_topic: "/next_block_cmd"
    odom_topic: "/odometry/filtered"
    cmd_vel_topic: "/cmd_vel"

    set_absolute_goal_service: "/set_absolute_goal"
    set_relative_goal_service: "/set_relative_goal"

    # =========================
    # 红外测距模块命令话题
    # =========================
    infrared_cmd_topic: "/step_cmd"

    # =========================
    # 导航与系统超时
    # =========================
    nav_timeout_sec: 60.0
    system_ready_timeout_sec: 80.0

    # =========================
    # 行为控制
    # =========================
    wait_for_cmd: false
    auto_delay_sec: 2.0
    enable_action: false
    action_prefix: "forest_arrive_"

    # =========================
    # 路径点序列
    # 注意：参数名必须是 waypoint_x / waypoint_y / waypoint_yaw
    # =========================
    waypoint_x: [-0.5, -0.5, -0.5, -0.5, -0.5, -3.095, -4.295, -4.295, -4.295, -4.295, -5.495, -6.695, -8.195, -8.195, -8.195, -8.195, -10.595, -10.595, -10.595]
    waypoint_y: [0.0, 0.0, -0.3, 1.56, 1.56, 1.56, 1.56, 1.56, 0.36, 0.36, 0.36, 0.36, 0.36, 0.36, 3.76, 3.76, 3.76, 3.76, 0.36]
    waypoint_yaw: [0.0, 1.57, 1.57, 1.57, 0.0, 0.0, 0.0, 1.57, 1.57, 3.14, 3.14, 3.14, 3.14, -1.57, -1.57, 0.0, 0.0, 1.57, 1.57]

    # 可选：不给也行，节点会自动生成 1,2,3...
    waypoint_ids: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

    # 可选：不给也行，节点会自动生成 P1, P2...
    waypoint_names: ["P1", "P2", "P3", "P4", "P5", "P6", "P7", "P8", "P9", "P10", "P11", "P12", "P13", "P14", "P15", "P16", "P17", "P18", "P19"]

    # =========================
    # 红外测距模块开关点
    # index 采用 1-based 序号
    # =========================
    infrared_on_indices: [6]
    infrared_off_indices: [13]

