r2_zone3_node:
  ros__parameters:

    start_signal_topic: /r2/zone3_start

    odom_topic: /odometry/filtered
    cmd_vel_topic: /cmd_vel
    goal_pose_topic: /r2/goal_pose

    absolute_goal_service: /set_absolute_goal
    use_lite_absolute_goal: true

    vision_priority_topic: /r2/vision_priority
    vision_offset_topic: /r2/vision_offset

    bottom_grid_result_topic: /r2/bottom_grid_result
    target_mid_grid_index_topic: /r2/target_mid_grid_index

    self_color: r
    bottom_kfs_select_strategy: center_first
    wait_bottom_grid_result_timeout_sec: 2.0

    mid_place_cmd_topic: /r2/mid_place_cmd
    mid_place_done_topic: /r2/mid_place_done

    high_place_cmd_topic: /r2/high_place_cmd
    high_place_done_topic: /r2/high_place_done

    r2_on_r1_topic: /r2/on_r1
    r1_move_done_topic: /r1/move_done

    can_tx_topic: /can_tx

    can_id_observe_bottom: 0x88
    can_cmd_observe_bottom: 0x02

    can_id_climb: 0x66
    can_cmd_climb: 0x03

    control_rate: 50.0

    nav_pos_tolerance: 0.05
    nav_yaw_tolerance: 0.05
    nav_execution_timeout: 30.0

    ramp_up_waypoint_index: 0
    face_grid_waypoint_index: 1
    mid_left_prep_waypoint_index: 2
    mid_right_prep_waypoint_index: 3
    r1_wait_waypoint_index: 4
    high_place_waypoint_index: 5

    vision_stable_count_required: 5

    max_vx: 0.25
    max_vy: 0.25
    max_wz: 0.6

    vision_kp_x: 1.0
    vision_kp_y: 1.0
    vision_kp_yaw: 1.5

    vision_mid_dx_threshold: 0.025
    vision_mid_dy_threshold: 0.025
    vision_mid_yaw_threshold: 0.05

    vision_lift_dx_threshold: 0.020
    vision_lift_dy_threshold: 0.030
    vision_lift_yaw_threshold: 0.04

    vision_high_dx_threshold: 0.025
    vision_high_dy_threshold: 0.025
    vision_high_yaw_threshold: 0.05

    wait_r2_on_r1_timeout_sec: 10.0
    wait_r1_move_done_timeout_sec: 20.0
    place_action_timeout_sec: 10.0

    # 0: 上坡进入三区点
    # 1: 朝向九宫格观察点
    # 2: 中层左放置预备点
    # 3: 中层右放置预备点
    # 4: R1 等待点
    # 5: 高层逻辑点
    #
    # 注意：
    # 2 和 3 坐标需要你按实车重新标定
    waypoints_x:   [10.59, 10.59, 10.30, 10.80, 8.60, 8.20]
    waypoints_y:   [-4.11, -4.11, -0.20, -0.20, 3.50, 3.50]
    waypoints_yaw: [-1.57, 1.57, 1.57, 1.57, 0.00, 0.00]

    waypoint_names:
      - ramp_up_point
      - face_grid_point
      - mid_left_prep_point
      - mid_right_prep_point
      - r1_wait_point
      - high_place_logic_point

